### ISSUE TITLE
[feature] Add a sorting option for `*include` 

### ISSUE THREAD

**Issue by adainese** [backstage/mkdocs-monorepo-plugin#124]
# Summary
Request to add a sorting option when including folders through the `*include` syntax
# Details
When including a set of folder using the `*include` syntax, they are added to the nav in lexicographic (default order of `ls`, I think).
I'd like to have some way to sort the entries in a different order, a couple of simple flags should be enough.
# Proposal
Just as an example, I can suggest something like this:
```yaml
# /mkdocs.yml
site_name: Cats System

nav:
  - Intro: 'index.md'
  - Components: '*include -n -r ./components/*/mkdocs.yml'
```
Where `-n` means using numerical order and `-r` means reverse order (same flags as `ls`)
