### ISSUE TITLE
Better support with `macros` plugin to override `extras`

### ISSUE THREAD

**Issue by Fokko** [backstage/mkdocs-monorepo-plugin#130]
I'm not sure if I should ask this here, or at the `macros` repository.

Consider the following setup:
```yaml
# /mkdocs.yml
site_name: Cats API

nav:
  - Intro: 'index.md'
  - Authentication: 'authentication.md'
  - API:
    - v1: '!include ./v1/mkdocs.yml'
    - v2: '!include ./v2/mkdocs.yml'

plugins:
  - monorepo

extras:
    version: v2  # default
```

```yaml
# /src/v1/mkdocs.yml
site_name: versions/v1

nav:
  - Reference: "reference.md"
  - Changelog: "changelog.md"

extras:
    version: v1
```

```yaml
# /src/v2/mkdocs.yml
site_name: versions/v2

nav:
  - Migrating to v2: "migrating.md"
  - Reference: "reference.md"
  - Changelog: "changelog.md"
```

I would love to have the version variable be overridden by the v1 in the earlier version, but it looks like the included extras are not evaluated.
