### ISSUE TITLE
Question about navigation

### ISSUE THREAD

**Issue by shinji62** [backstage/mkdocs-monorepo-plugin#65]
Hello there,

First thanks for this incredibly useful plugin, I have 2 question related to navigation

1- Can we setup the [navigations tabs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs) by subdirectory ? if yes how 
2- Can we have an index page on the submenu, if you looks at the attachement we need an HOME under each submenu where we will prefer to have a page on the submenu link itself (like End User, Cloud and Devops)  ?

Thanks

**Comment by wilhelmer** [comment]
Not sure what you mean, do you need this to be done automatically? E.g., you create subdir1, subdir2, and subdir3, and they automatically appear as navigation tabs? I don't think that's possible.

However, you can easily define that manually in your `mkdocs.yml`:

```yml
nav:
    - Home:
        - Tab 1: '!include ./subdir1/mkdocs.yml'
        - Tab 2: '!include ./subdir2/mkdocs.yml'
```
