### ISSUE TITLE
Error when no `nav` and `docs_dir` are specified

### ISSUE THREAD

**Issue by dariocurr** [backstage/mkdocs-monorepo-plugin#81]
I was trying to build my monorepo documentation having the following in the general `mkdocs.yml`
``` yaml
site_name: "Example"
site_description: "Description Here"

docs_dir: ./docs

plugins:
  - monorepo

nav:
  - Home: "index.md"
  - Subnav:
    - index.md
    - index.md
  - Hello: "!include project-a/mkdocs.yml"
```

and the following `mkdocs.yml` in a subfolder of the monorepo

```yaml
site_name: "test"
site_description: "This is a subdomain site."

plugins:
  - monorepo
```

And I got this error: 

_The file path .... does not contain a valid 'nav' key in the YAML file and the docs folder is not the default one, i.e. `docs`. Please include the `nav` key to indicate how your documentation should be presented in the navigation, or include a 'docs_dir' to indicate that automatic nav generation should be used._

I personally find useless to specify the key `docs_dir` when it is the default one, i.e.  `docs`.  
I would like to have the automatic nav generation without having to specify the `docs_dir` key
