### ISSUE TITLE
Merge subdirectories into the same tree?

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [backstage/mkdocs-monorepo-plugin#85]
I have a repo with multiple directories with individual READMEs and mkdocs.yml e.g.:

```
|-core
   |-docs
      -mkdocs.yml
      |-README.md
```

```
site_name: core
nav: 
  - Networking: README.md
```

I have included them in my nav so that it looks like:

```
nav:
  - Overview: 'README.md'
  - Implementation: 'IMPLEMENTATION.md'
  - Infrastructure: 
    - Networking: '!include ./core/mkdocs.yml'
    - Metadata: '!include ./metadata/mkdocs.yml'
    - Extraction: '!include ./pipelines/mkdocs.yml'
    - Glue: '!include ./glue_database/mkdocs.yml'
```
This creates the following output: 
![image](https://user-images.githubusercontent.com/95432492/191086518-04c8f689-585e-4fc9-ac12-2273432943cf.png)

I was wondering if there was a way of merging contents into a single output tree so that the individual headers are not duplicated e.g.:
```
Infrastructure
  - Networking
  - Metadata
  - Extraction
  - Glue
```

**Comment by SoumayaMauthoorMOJ** [comment]
This is possible using `navigation.indexes` with mkdocs materials: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages

**Comment by vshivam** [comment]
Hi @SoumayaMauthoorMOJ, might you have a sample of what your `mkdocs.yml` files look like now ? I am trying to achieve exactly this but unable to get the desired result. Thanks!

**Comment by SoumayaMauthoorMOJ** [comment]
Unfortunately I can't share the repo because it's internal but here's the relevant mkdocs section:
```
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

nav:
  - Home: 
    - 'README.md'
    - Architecture: 'architecture.md'
    - Deployment: 'cicd.md'
  - Components:
    - 'components/README.md'
    - Networking: '!include ./core/mkdocs.yml'
    - Metadata: '!include ./metadata/mkdocs.yml'
    - Extraction: '!include ./pipelines/mkdocs.yml'
    - Glue: '!include ./glue_database/mkdocs.yml'
  - Contributing: 
    - 'contributing/README.md'
    - Using Pulumi: contributing/using_pulumi.md

 ```
Here's a screenshot of the repo structure:

![image](https://user-images.githubusercontent.com/95432492/229344558-06fc37b9-6068-46a5-8776-ea22bcb10b6a.png)

And here's the link to the website which is public: https://ministryofjustice.github.io/analytical-platform-data-engineering/

The sub-pages under the [Components](https://ministryofjustice.github.io/analytical-platform-data-engineering/components/) page are all merged as desired:
![image](https://user-images.githubusercontent.com/95432492/229344646-999cdded-c740-4f5f-917b-9313436fa9b9.png)

Hope that helps!
