### ISSUE TITLE
Unable to use includes 

### ISSUE THREAD

**Issue by ssbarnea** [backstage/mkdocs-monorepo-plugin#92]
On child projects we use includes for files that need to be at project root, like `README.md` or `CHANGELOG.md` and this is achieved using 

```md
<!-- docs/changelog.md -->
{!../CHANGELOG.md!}
```

```yaml
# child mkdocs.yml file
plugins:
  - markdown_include.include:
      base_path: docs
```

While this works when building docs of each child-site, it does not work with monorepo plugin.

I mention that our initial attempt was to use symlinks from docs/ to parent but that does not work with mkdocs either, being forced to use the include method. Also creating symlinks from root to docs/ folder does not work because github does not display these markdown files correctly.

Related: https://github.com/cmacmackin/markdown-include/issues/41
