### ISSUE TITLE
monorepo with submodules (empty)

### ISSUE THREAD

**Issue by dhabierre** [backstage/mkdocs-monorepo-plugin#98]
Hi,

I am playing with monorepo plugin.
I have 1 repo (rpa-doc) with 2 submodules (rpa-1, rpa2):

```
rpa-doc
- docs \ README.md
- .gitmodules
- catalog-info.yml
- mkdocs.yml
- rpa-1 @ d70d...
- rpa-2 @ dbe6...
```

**mkdocs.yml**

```yml
site_name: RPA Documentation (Test)

nav:
  - Home: README.md
  - Submodules:
    - rpa-1: '!include ./rpa-1/mkdocs.yml'
    - rpa-2: '!include ./rpa-2/mkdocs.yml'

plugins:
  - monorepo
```

**rpa-1 @ d70d...**

```
- docs \ README.md
- mkdocs.yml
```

When backstage executes the doc generation:

```
[mkdocs-monorepo] The file path /tmp/backstage-QFfxej/rpa-1/mkdocs.yml does not exist, is not valid YAML, or does not contain a valid 'site_name' and 'nav' keys.
```

And `/tmp/backstage-QFfxej/rpa-1/mkdocs.yml` does not exist.
=> Submodules folders are empty.

I think the clone action does not use the `--recursive` attribute.

Locally:

```
git clone https://bitbucket.[xxx].[xxx]/scm/tests/rpa-doc.git --recursive
```

=> [OK] submodules are pulled and mkdocks.yml files exist.

```
git clone https://bitbucket.[xxx].[xxx]/scm/tests/rpa-doc.git
```

=> [KO] submodules are empty

Any idea?
Thanks!
